### ISSUE TITLE
Order of command line arguments to Coq

### ISSUE THREAD

**Issue by gmalecha** [hannesm/Kopitiam#46]
The order of command line arguments to coqc should be reversed. For example, right now the Makefile produces calls like:

coqc -R src "" -R bin "" -R path/to/other/lib Lib ...

the "-R src "" -R bin """ should go last in the list so that Coq looks for files in those directories first.

While the real way to do this is to never use -R (is there an option for this now?) for including outside projects the order of arguments should still be fixed (it shouldn't be too difficult right?)

**Comment by ale-f** [comment]
Fixed in commit c83cf02da118dd5bf8a77c086cb6e0c3000aa4dc.
