### ISSUE TITLE
Error message for incomplete proof does not disappear.

### ISSUE THREAD

**Issue by jesper-bengtson** [hannesm/Kopitiam#91]
When proving the following lemma 

```
Lemma test : True.
Qed.
```

Coqoon will rightly complain that we are trying to Qed an incomplete proof. However, the error message does not go away when 

```
apply I.
```

is inserted to prove the lemma, but only once the Qed line has been edited.

**Comment by ale-f** [comment]
Like (part of) issue #90, using the `Coq-0.2.0` version of PIDEtop fixes this problem; closing.
