### ISSUE TITLE
Error markers are not updated when lemma definition changes

### ISSUE THREAD

**Issue by jesper-bengtson** [hannesm/Kopitiam#94]
Take the following lemma

```
Lemma Test : False.
  apply I.
Qed.
```

This will correctly display an error marker on ```apply I```. Fix the lemma by changing it to

```
Lemma Test : True.
  apply I.
Qed.
```

The proof is updated (stepping through the code with the cursor does the right thing, even for more complex proofs), but the error marker stays in place.

**Comment by ale-f** [comment]
Whoops! This *was* actually a bug in Coqoon: the code assumed that errors could only disappear when their commands disappeared. Fixed in commit e7584f4e5f41099e9cd89d9ba8c4e215bd1ffcc1.
